### ISSUE TITLE
Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by dyakhnov** [appbaseio/dejaVu#102]
Windows 10 (64-bit)
Node 8.0.0
npm 5.0.0

>npm install

```
7898 silly extract miller-rabin@4.0.0
7899 silly pacote trying miller-rabin@https://registry.npmjs.org/miller-rabin/-/miller-rabin-4.0.0.tgz by hash: sha1-SmL7HUKTPAVYOYL0xxb2+55sbT0=
7900 verbose stack TypeError: Cannot read property 'find' of undefined
7900 verbose stack     at opts.integrity.digests.find.hash (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:262:33)
7900 verbose stack     at Array.find (native)
7900 verbose stack     at Transform.on (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:261:15)
7900 verbose stack     at emitNone (events.js:110:20)
7900 verbose stack     at Transform.emit (events.js:207:7)
7900 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
7900 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
7900 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
7901 verbose cwd C:\lab\elk\dejavu
7902 verbose Windows_NT 10.0.15063
7903 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
7904 verbose node v8.0.0
7905 verbose npm  v5.0.0
7906 error Cannot read property 'find' of undefined
7907 verbose exit [ 1, true ]

```

**Comment by dyakhnov** [comment]
Close this ticket please, NodeJS has been upgraded to 8.4.0 and that was it!
