### ISSUE TITLE
Cannot build dejavu locally, pngquant failed to build (centos 7)

### ISSUE THREAD

**Issue by ghost** [appbaseio/dejaVu#211]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
Hosted web app

#### What is the version of Dejavu that you are using?
dev

[me@mapr07 dejavu]# git describe --tags
1.6.1-8-gb2ef533

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
Following the instructions to build locally (https://github.com/appbaseio/dejavu/blob/dev/CONTRIBUTING.md), when running command `npm install`, seeing:

```
[me@mapr07 dejavu]$ npm install

> pngquant-bin@4.0.0 postinstall /home/me/dejavu/node_modules/pngquant-bin
> node lib/install.js

(node:24364) ExperimentalWarning: The fs.promises API is experimental
  ⚠ The `/home/me/dejavu/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/home/me/dejavu/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2018-05-16T20_31_30_535Z-debug.log
```

Yet when trying to install `libpng-dev`, only have the option of installing `libpng-devel` (on centos 7).

```
[root@mapr07 dejavu]# yum info libpng*
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.sonic.net
 * epel: mirror.compevo.com
 * extras: repos.lax.quadranet.com
 * updates: mirror.scalabledns.com
Installed Packages
Name        : libpng
Arch        : x86_64
Epoch       : 2
Version     : 1.5.13
Release     : 7.el7_2
Size        : 602 k
Repo        : installed
From repo   : base
Summary     : A library of functions for manipulating PNG image format files
URL         : http://www.libpng.org/pub/png/
License     : zlib
Description : The libpng package contains a library of functions for creating
            : and manipulating PNG (Portable Network Graphics) image format
            : files.  PNG is a bit-mapped graphics format similar to the GIF
            : format.  PNG was created to replace the GIF format, since GIF uses
            : a patented data compression algorithm.
            : 
            : Libpng should be installed if you need to manipulate PNG format
            : image files.

Name        : libpng-devel
Arch        : x86_64
Epoch       : 2
Version     : 1.5.13
Release     : 7.el7_2
Size        : 211 k
Repo        : installed
From repo   : base
Summary     : Development tools for programs to manipulate PNG image format
            : files
URL         : http://www.libpng.org/pub/png/
License     : zlib
Description : The libpng-devel package contains header files and documentation
            : necessary for developing programs using the PNG (Portable Network
            : Graphics) library.
            : 
            : If you want to develop programs which will manipulate PNG image
            : format files, you should install libpng-devel.  You'll also need
            : to install the libpng package.

Available Packages
Name        : libpng
Arch        : i686
Epoch       : 2
Version     : 1.5.13
Release     : 7.el7_2
Size        : 215 k
Repo        : base/7/x86_64
Summary     : A library of functions for manipulating PNG image format files
URL         : http://www.libpng.org/pub/png/
License     : zlib
Description : The libpng package contains a library of functions for creating
            : and manipulating PNG (Portable Network Graphics) image format
            : files.  PNG is a bit-mapped graphics format similar to the GIF
            : format.  PNG was created to replace the GIF format, since GIF uses
            : a patented data compression algorithm.
            : 
            : Libpng should be installed if you need to manipulate PNG format
            : image files.

Name        : libpng-devel
Arch        : i686
Epoch       : 2
Version     : 1.5.13
Release     : 7.el7_2
Size        : 122 k
Repo        : base/7/x86_64
Summary     : Development tools for programs to manipulate PNG image format
            : files
URL         : http://www.libpng.org/pub/png/
License     : zlib
Description : The libpng-devel package contains header files and documentation
            : necessary for developing programs using the PNG (Portable Network
            : Graphics) library.
            : 
            : If you want to develop programs which will manipulate PNG image
            : format files, you should install libpng-devel.  You'll also need
            : to install the libpng package.

Name        : libpng-static
Arch        : i686
Epoch       : 2
Version     : 1.5.13
Release     : 7.el7_2
Size        : 91 k
Repo        : base/7/x86_64
Summary     : Static PNG image format file library
URL         : http://www.libpng.org/pub/png/
License     : zlib
Description : The libpng-static package contains the statically linkable version
            : of libpng. Linking to static libraries is discouraged for most
            : applications, but it is necessary for some boot packages.

Name        : libpng-static
Arch        : x86_64
Epoch       : 2
Version     : 1.5.13
Release     : 7.el7_2
Size        : 92 k
Repo        : base/7/x86_64
Summary     : Static PNG image format file library
URL         : http://www.libpng.org/pub/png/
License     : zlib
Description : The libpng-static package contains the statically linkable version
            : of libpng. Linking to static libraries is discouraged for most
            : applications, but it is necessary for some boot packages.

Name        : libpng12
Arch        : i686
Version     : 1.2.50
Release     : 10.el7
Size        : 174 k
Repo        : base/7/x86_64
Summary     : Old version of libpng, needed to run old binaries
URL         : http://www.libpng.org/pub/png/
License     : zlib
Description : The libpng12 package provides libpng 1.2, an older version of the
            : libpng library for manipulating PNG (Portable Network Graphics)
            : image format files. This version should be used only if you are
            : unable to use the current version of libpng.

Name        : libpng12
Arch        : x86_64
Version     : 1.2.50
Release     : 10.el7
Size        : 171 k
Repo        : base/7/x86_64
Summary     : Old version of libpng, needed to run old binaries
URL         : http://www.libpng.org/pub/png/
License     : zlib
Description : The libpng12 package provides libpng 1.2, an older version of the
            : libpng library for manipulating PNG (Portable Network Graphics)
            : image format files. This version should be used only if you are
            : unable to use the current version of libpng.

Name        : libpng12-devel
Arch        : i686
Version     : 1.2.50
Release     : 10.el7
Size        : 111 k
Repo        : base/7/x86_64
Summary     : Development files for libpng 1.2
URL         : http://www.libpng.org/pub/png/
License     : zlib
Description : The libpng12-devel package contains header files and documentation
            : necessary for developing programs using libpng12.

Name        : libpng12-devel
Arch        : x86_64
Version     : 1.2.50
Release     : 10.el7
Size        : 111 k
Repo        : base/7/x86_64
Summary     : Development files for libpng 1.2
URL         : http://www.libpng.org/pub/png/
License     : zlib
Description : The libpng12-devel package contains header files and documentation
            : necessary for developing programs using libpng12.
```

Installing `libpng-devel`, still getting same error. Manually installing `pngquant` via `yum` also does not help.

**Comment by divyanshu013** [comment]
Not sure about centos but this works fine on Fedora 27. I can suggest a few things you can try:

1. Check your node version. If its old, update to the latest stable atleast.
2. Do a fresh clone and use `yarn` instead of `npm` (Just run `yarn` in the project directory after cloning)
3. Run `bower install` (You will need `bower` as a global module first - `npm i -g bower`

**Comment by ghost** [comment]
Thanks.
Using `yarn` instead of `npm` allowed me to get around the issue.
Note for others, I ran into a naming conflict between the `yarn` package manager and `yarn` for apache hadoop (see https://github.com/yarnpkg/yarn/issues/2337). Ended up downloading the `yarn` package manager .tar.gz file, and calling the local `yarnpkg` binary from inside the dejavu project folder.
