### ISSUE TITLE
Error on case-sensitive platforms

### ISSUE THREAD

**Issue by andrew-ie** [appbaseio/dejaVu#31]
Hi,

I tried to deploy this application locally on a Linux environment, and it failed to launch with an error:

```
[09:13:26] Using gulpfile /tmp/dejaVu/gulpfile.js
[09:13:26] Starting 'browserify'...
[09:13:26] Starting 'connect'...
[09:13:26] Finished 'connect' after 6.67 ms
[09:13:26] Server started http://localhost:1358
[09:13:26] LiveReload started on port 35729
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './homePage.jsx' from '/tmp/dejaVu/_site/src/js'
    at /tmp/dejaVu/node_modules/resolve/lib/async.js:55:21
    at load (/tmp/dejaVu/node_modules/resolve/lib/async.js:69:43)
    at onex (/tmp/dejaVu/node_modules/resolve/lib/async.js:92:31)
    at /tmp/dejaVu/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Checking the src/js folder, I can see that it contains a file "HomePage.jsx"

For some preliminary checks so that it at least starts up - I renamed (locally):

Old Name | New Name
-------- | --------
features/FeatureComponent.jsx | features/featureComponent.jsx
HomePage.jsx | homePage.jsx
table/fieldCheckbox.jsx | table/FieldCheckbox.jsx
TypeTable.jsx | typeTable.jsx

However, I'd recommend a more permanent fix of standardizing the filenames to be a specific case, and modify either the code referencing it, or the file name to suit whichever this standard is.

**Comment by siddharthlatest** [comment]
Are you building from the ``dev`` branch or a particular release?

**Comment by andrew-ie** [comment]
Hi - this was straight from dev - checked out this morning.

**Comment by siddharthlatest** [comment]
@andrew-ie thanks, able to replicate the issue.

**Comment by farhan687** [comment]
Fixed: a28b8759b24b35ec0d19a2e81698d744daeac23d

**Comment by andrew-ie** [comment]
Hi,

It looks like there is still one left:

```
[08:00:09] Using gulpfile /tmp/dejaVu/gulpfile.js
[08:00:09] Starting 'browserify'...
[08:00:09] Starting 'connect'...
[08:00:09] Finished 'connect' after 72 ms
[08:00:09] Server started http://localhost:1358
[08:00:09] LiveReload started on port 35729
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './dropdown.jsx' from '/tmp/dejaVu/_site/src/js/table'
    at /tmp/dejaVu/node_modules/resolve/lib/async.js:55:21
    at load (/tmp/dejaVu/node_modules/resolve/lib/async.js:69:43)
    at onex (/tmp/dejaVu/node_modules/resolve/lib/async.js:92:31)
    at /tmp/dejaVu/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

If I edit the file DataTable.jsx and replace dropdown.jsx with Dropdown.jsx, then it starts up correctly.

**Comment by farhan687** [comment]
@andrew-ie Should be fixed now with this commit: https://github.com/appbaseio/dejaVu/commit/1195a20338a3cbf636a8c45800b829aa7ca31be9

Can you please check it?

**Comment by andrew-ie** [comment]
@farhan687 Yes - it now launches correctly.

Thanks for fixing this!
