### ISSUE TITLE
Unable to export data

### ISSUE THREAD

**Issue by wangwalton** [appbaseio/dejaVu#335]
Export CSV doesn't work, export JSON downloads a text file with 'undefined'

**Comment by lakhansamani** [comment]
@wangwalton can you share if there are any console errors?

**Comment by DaiZack** [comment]
Same issue Using self hosted ES 8.1.0

main.5f8d78f2.js:2          POST http://10.8.1.245:9200/coface/_search 400 (Bad Request)
a @ main.5f8d78f2.js:2
i @ main.5f8d78f2.js:2
s @ main.5f8d78f2.js:2
(anonymous) @ main.5f8d78f2.js:2
(anonymous) @ main.5f8d78f2.js:2
t.handleClick @ common.09e89551.js:2
h @ common.09e89551.js:2
w @ common.09e89551.js:2
(anonymous) @ common.09e89551.js:2
k @ common.09e89551.js:2
T @ common.09e89551.js:2
x @ common.09e89551.js:2
N @ common.09e89551.js:2
Sn @ common.09e89551.js:2
ue @ common.09e89551.js:2
Tn @ common.09e89551.js:2
_n @ common.09e89551.js:2
Nn @ common.09e89551.js:2
c.unstable_runWithPriority @ main.5f8d78f2.js:2
Ko @ common.09e89551.js:2
ce @ common.09e89551.js:2
xn @ common.09e89551.js:2
main.5f8d78f2.js:2 SEARCH ERROR Error: HTTP STATUS: 400 - Unable to get count
    at a (main.5f8d78f2.js:2:3766960)
    at async i (main.5f8d78f2.js:2:1058840)
    at async s (main.5f8d78f2.js:2:1059898)
    at async V.fetchData (main.5f8d78f2.js:2:3638763)
    at async main.5f8d78f2.js:2:3640070
