### ISSUE TITLE
git not installed in node docker image

### ISSUE THREAD

**Issue by matthewberryman** [appbaseio/dejaVu#72]
running docker build (for dev branch) generates an error on npm install as git is not installed in the docker node image:
```
Step 9/12 : RUN bower install --allow-root
 ---> Running in cda85a1e1693
bower urlsafe-base64#*          ENOGIT git is not installed or not in the PATH
```

Just flagging that on master there's a separate docker install issue
```
[06:18:10] Finished 'vendorcss' after 738 ms
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './FilterDropdown.jsx' from '/project/_site/src/js/table'
    at /project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:114:15)
The command '/bin/sh -c gulp' returned a non-zero code: 1
```
that I haven't raised as an issue as it's gone away in your dev branch

**Comment by siddharthlatest** [comment]
Fixed in 3a34220f9d4c6f962608c90ef2635fc111216498.
