### ISSUE TITLE
main.min.js:1 Uncaught TypeError: this.generateFilterQuery is not a function

### ISSUE THREAD

**Issue by isgroup-srl** [appbaseio/dejaVu#85]
When a filter of type "search" is set the "Export" button does not work, with the following exception:

```
Uncaught TypeError: this.generateFilterQuery is not a function
    at t.getQueryBody (http://127.0.0.1:1358/dist/main.min.js:1:7421)
    at t.exportJsonData (http://127.0.0.1:1358/dist/main.min.js:1:22997)
    at t.open (http://127.0.0.1:1358/dist/main.min.js:2:22433)
    at Object.o.invokeGuardedCallback (http://127.0.0.1:1358/dist/main.min.js:15:16398)
    at s (http://127.0.0.1:1358/dist/main.min.js:12:21771)
    at Object.i [as executeDispatchesInOrder] (http://127.0.0.1:1358/dist/main.min.js:12:22018)
    at f (http://127.0.0.1:1358/dist/main.min.js:12:16782)
    at m (http://127.0.0.1:1358/dist/main.min.js:12:16908)
    at Array.forEach (native)
    at r (http://127.0.0.1:1358/dist/main.min.js:17:21744)
    at Object.processEventQueue (http://127.0.0.1:1358/dist/main.min.js:12:18205)
```

**Comment by siddharthlatest** [comment]
@isgroup-srl We just pushed a new build. It should work now, let us know if you still see the issue.

**Comment by isgroup-srl** [comment]
Thanks, will check on monday!

**Comment by siddharthlatest** [comment]
@isgroup-srl Were you able to verify? I am closing the issue, feel free to re-open if you still see the exception.
